[main]
# Solo JetBrains Mono, dimensione ridotta a 12
font=JetBrains Mono:size=9
prompt="> "

# Niente icone
icons-enabled=no

# Dimensioni: 5 righe di altezza, 50 caratteri di larghezza
lines=5
width=40

# Spaziatura 
horizontal-pad=15
vertical-pad=10
inner-pad=5

[colors]
background=1a1a1aff
text=ffffffff
match=ccccccff
selection=ffffffff
selection-text=1a1a1aff
selection-match=000000ff
border=ffffffff

[border]
width=2
radius=0
